name: HotsSG
main: net.hotsmc.sg.HSG
version: 1.0
loadbefore: [HotsCore]
softdepend: [HotsCore]
commands:
  hsg:
  sidebar:
  spec:
  stats:
  bounty:
  list:
    aliases: [l]
  vote:
    aliases: [v]